package sec1;

public class ExceptionExam4 {
	public static void main(String[] args) {
		String data1 = "1004";
		String data2 = "김기태";
		
		try {
			int val1 = Integer.parseInt(data1);
			int val2 = Integer.parseInt(data2);
		}catch(NumberFormatException e) {
			System.out.println("숫자아님");
			e.printStackTrace();
		}catch(Exception e) {
			System.out.println("오류발생");
			e.getMessage();
		}finally {
			System.out.println("종료");
		}
	}
}
